version: '3.7'

services:

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    build:
      context: .
    ports:
      - 4380:80
    volumes:
      - /volume1/docker/akaunting/data:/var/www/html:rw
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP=true
    depends_on:
      - akaunting-db

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - /volume1/docker/akaunting/db:/var/lib/mysql:rw
    restart: unless-stopped
    env_file:
      - env/db.env

 
